### PR TITLE
minor improvement

### PR DESCRIPTION
**Pull request by valq7711**
To avoid errors in shell maybe we should  `if not app_name: use_appname = False` ?

### CODE REVIEW

**Review by paolopas — APPROVED** [review]

**Comment by paolopas** [comment]
For the extra if, I agree.
Let me say just one thing about the URL function:
I see very often inline (... if ... else ...) construct used, this has the taste of a patch over the patch over the patch...

**Comment by valq7711** [comment]
yes, it is so ... especially last line. 
As for me, js-notation looks clearer `some = cond ? yes : no`
since it has the same structure as regular `if/else`:
```python
if cond:
    yes 
else:
    no
```

**Comment by paolopas** [comment]
Works fine, there are not errors, I am not sure about the extra
`if not app_name: use_appname = False ?`
because make use_appname even more "overloaded".
Let me do a final cleanup

**Comment by paolopas** [comment]
Works fine, there are not errors, I am not sure about the extra
`if not app_name: use_appname = False ?`
because make use_appname even more "overloaded".
Let me do a final cleanup

**Comment by valq7711** [comment]
I mean if we are in shell then  there is no app_name and just `URL('path/to/here')` without `use_appname = False` will fails, no?
So if we do `if not app_name: use_appname = False` it will still work

**Comment by paolopas** [comment]
does not, it uses the "None" app_name instead,
in my last version I changed a couple of conditions to avoid that, avoid altering use_appname again.

**Pull request merged**
