### PR TITLE
speedup + more safe

### PR DESCRIPTION
**Pull request by valq7711**

### CODE REVIEW

**Review by paolopas — APPROVED** [review]

**Comment by paolopas** [comment]
@valq7711 in core.py I can find `x-py4web-appname` in other 2 places:

1. monkey_patch_bottle function (+138), and
2. error404 function (+1130)

**Comment by valq7711** [comment]
yes, bottle has a dozen ways to access headers (why?), but `request.environ.get()` is fastest  since it does not do any transformation (`request.environ` - is a direct refernce to dict that comes from wsgi server)

**Comment by paolopas** [comment]
@valq7711
Was my mistake to accept your PR because changing
`request.headers.get("x-py4web-appname")`
with
`request.environ.get("HTTP_X_PY4WEB_APPNAME")`
has the subtle side effect to introduce an alias for x-py4web-appname.

Before that was possible to search for all place where you are looking for application mapped domain into the code with a simple unix grep (find.exe on windows), but now this is not more possible without searching for both words (x-py4web-appname and HTTP_X_PY4WEB_APPNAME).

I am not interested on (but I know) the Bottle internals.

The fact that environ.get("HTTP_X_PY4WEB_APPNAME") is faster than headers.get("x-py4web-appname") is bad balanced by the lack of consistency.

**We should either restore previous request.headers.get("x-py4web-appname") into URL function or substitute x-py4web-appname everywhere.**

**Comment by valq7711** [comment]
I am for a replacement with `HTTP_X_PY4WEB_APPNAME` everywhere.

**Comment by valq7711** [comment]
@paolopas 
Also, uppercase with HTTP_X-prefix meets wsgi python PEP notation, so why should we use bottle one?

**Comment by paolopas** [comment]
I am for using the most common one, in the sense of _most developer-intuitive form_, suppose that in the future someone will need to write that condition again? How do he/she will likely do it without having any knowledge of our discussion?

**Comment by valq7711** [comment]
The most intuitive form is "X-Py4web-Appname")))))). There is PEP,  bottle fights it, believing that it makes life easier, but complicates it, allowing you to do the same things in different ways.

**Comment by valq7711** [comment]
I think py4web (at least) should meet PEP

**Comment by valq7711** [comment]
we can introduce py4web global var like `APPNAME_HEADER = '...'` and use it everywhere

**Comment by paolopas** [comment]
Ok, let it be `HTTP_X_PY4WEB_APPNAME`, no need for global var.
Please, can you make a PR with the other 2 substitutions ?

**Comment by paolopas** [comment]
@valq7711 Do you think to make a PR?

**Comment by valq7711** [comment]
Yes, but have no time :(


чт, 21 янв. 2021 г. в 17:49, Paolo Pastori <notifications@github.com>:

**Pull request merged**
